ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MINUTES_SAVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MINUTES_PUBLISHED';

ALTER TABLE "Meeting" ADD COLUMN "minutesUpdatedAt" TIMESTAMP(3);
ALTER TABLE "Meeting" ADD COLUMN "minutesPublished" BOOLEAN NOT NULL DEFAULT false;
